# generated by datamodel-codegen:
#   filename:  example_schema.json
#   timestamp: 2024-10-29T16:47:26+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class 分類(BaseModel):
    主要: str
    次要: str
    類型: str


class 活動列表Item(BaseModel):
    日期: str
    時間: str
    地點: str


class 活動場次Item(BaseModel):
    場次: str
    主題: str
    活動列表: List[活動列表Item]


class 活動報名(BaseModel):
    報名對象: Optional[str] = None
    報名時間: Optional[str] = None


class Model(BaseModel):
    活動鏈接: str
    分類: 分類
    活動名稱: str
    活動單位: str
    活動網址: Optional[str] = None
    活動日期及時間: str
    活動地點: str
    活動描述: Optional[str] = None
    活動場次: List[活動場次Item]
    活動報名: Optional[活動報名] = None
